version: "3.7"
services:
    webapp:
        image: registry.everytrade.io/webapp:2020-07-28
        volumes:
            - webapp-data:/opt/jboss/everytrade
        ports:
            - "127.0.0.1:8080:8080"
        environment:
            EVERYTRADE_DB_HOST: db
            EVERYTRADE_DB_USER: everytrade
            EVERYTRADE_DB_PASSWORD: everytrade
        depends_on:
            - db
        restart: unless-stopped
    db:
        image: registry.everytrade.io/mysql:8.0.21
        volumes:
            - db-data:/var/lib/mysql
        expose:
            - "3306"
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: everytrade
            MYSQL_USER: everytrade
            MYSQL_PASSWORD : everytrade
        restart: unless-stopped
#    debug:
#        image: registry.everytrade.io/ubuntu:20.04
volumes:
    db-data:
    webapp-data: